### PR TITLE
updated the vendetta client do to drama

### PR DESCRIPTION
**Pull request by lexyclear**
Drama led to this/ Dont trust the Vendetta dev. thank you. nor his plugins. if you see anything else he has worked on at me on discord with proof.

### CODE REVIEW

**Comment by SL4F** [comment]
don't trust them for adding their name in a single line to check if enmity was stealing from them?

**Comment by AAGaming00** [comment]
fiery isn't even the vendetta dev 💀 that's beef

**Comment by SL4F** [comment]
I love malware!

**Comment by Juby210** [comment]
Hey, this is literally a false claim made by enmity developers. Please revert this commit.

**Comment by SL4F** [comment]
enmity also has malware picture below is proof 
Screenshot_20230501-213111

**Comment by Meqativ** [comment]
> enmity also has malware picture below is proof Screenshot_20230501-213111

enmity exposed while trying to expose vendetta

**Comment by VaiCaDep0893** [comment]
Listen here, you little piece of shit. Just because of a silly drama doesn't mean you have to change from "Active" to a fucking "malicious". Change it back to normal,

**Comment by VaiCaDep0893** [comment]
@lexyclear Make sure you see this, you piece of shit

**Comment by Meqativ** [comment]
> Listen here, you little piece of shit. Just because of a silly drama doesn't mean you have to change from "Active" to a fucking "malicious". Change it back to normal,
> @lexyclear Make sure you see this, you piece of shit
why u so angry they just tryna keep people safe while seeing stuff only from one side

**Comment by lexyclear** [comment]
honestly fixed the issue, i only got info from one side, after seeing the full pic and info going on sorry 
enmity stole code and has been updated to show this reverted vendetta back. sorry for the trouble.

**Comment by skff-err** [comment]
hi guys :3

**Comment by AAGaming00** [comment]
enmity didn't steal code either, they just took fiery's dumped ipas. don't mean to worsen their reputation from this

**Comment by SL4F** [comment]
yeah, and firey only did it to see if they were using their ipa's (I say it's fierys since they did the work, which should have had credit somewhere considering it's an open source project)

**Comment by acquitelol** [comment]
maybe just close this pr. the "drama" is not worth changing either client mod's info and it really wasnt as big of a deal as it was made to be.

**Comment by acquitelol** [comment]
> enmity also has malware picture below is proof
> Screenshot_20230501-213111

horror

**Comment by lexyclear** [comment]
no more comments please. on this topic.

**Pull request merged**
