### PR TITLE
Update Bluecord section

### PR DESCRIPTION
**Pull request by bluemods**
It's not closed source nor malware, the GitHub repos are linked even before this PR, which makes that statement baffling.

https://github.com/bluemods/Bluecord
https://github.com/bluemods/BluecordPatcher

### CODE REVIEW

**Comment by lexyclear** [comment]
considering past actions you have done with proof. i disagree.

**Comment by bluemods** [comment]
So you're going to continue to label it closed source and malware, despite both of these statements being patently false. Got it. Such a nice community, this is.

**Comment by NTBBloodbath** [comment]
Both you and your software have a demonstrably bad reputation, and saying your code is open-source doesn't make it trustworthy. For example, the same tech company that offers one of the most open-source browsers also has the largest ads and tracking network in history, with that browser playing a significant role in it (and we all know very well what company it is).

**Comment by bluemods** [comment]
> Both you and your software have a demonstrably bad reputation, and saying your code is open-source doesn't make it trustworthy. For example, the same tech company that offers one of the most used open-source browsers also has the largest ads and tracking network in history, with that browser playing a significant role in it (and we all know very well what company it is).

Pretty much all the 'proof' are fabrications done by one person as part of a slander campaign, and what he's leaving out is the doxxing and swatting he's engaged in, against me. This repo is contributing to that campaign, by listing completely inaccurate statements.
Google is a wildly successful company, so I appreciate that comparison.

Please show me where the malware is.

**Comment by lexyclear** [comment]
Dude. nobody trust you. nobody.

**Comment by lexyclear** [comment]
we are not going to allow software that use to be malware that let you bot peoples accounts. 
yes we have proof of that in the google drive linked. 
sorry. we keep our users safe.

**Comment by bluemods** [comment]
> we are not going to allow software that use to be malware that let you bot peoples accounts. yes we have proof of that in the google drive linked. sorry. we keep our users safe.

Can you link to where my software does that in the repo?

**Comment by lexyclear** [comment]
if you want to discuss this like adults there is the discord server. otherwise keep bitching a closed thread.

**Comment by bluemods** [comment]
You can't link to it because it simply doesn't exist. Please feel free to prove me wrong.

**Comment by lexyclear** [comment]
whats this?
https://drive.google.com/drive/u/0/folders/1Y2m2lMSpN3GlOcXyceaO88Ljnr8xuNcp
oh yeah we are wrong. haha

**Comment by lexyclear** [comment]
Yeah cause i went through all this trouble to make a organized wiki just to dunk on you.
that was my evil plan.
to ruin the creator of blues cord life.

**Comment by lexyclear** [comment]
what kind of 2nd grade logic is that.

**Comment by bluemods** [comment]
Already explained https://github.com/Discord-Client-Encyclopedia-Management/Discord3rdparties/pull/109#issuecomment-1742200830

Please show evidence that Bluecord is malware. You cannot. You are simply contributing to the campaign, and engaging in libel. I'm sorry you can't see past your convictions and I hope you will discontinue making false statements.

**Comment by lexyclear** [comment]
whats in the github then huh?
https://drive.google.com/drive/u/0/folders/1Y2m2lMSpN3GlOcXyceaO88Ljnr8xuNcp

**Comment by lexyclear** [comment]
Just gonna say this now.
unless you get like Ven or another trusted client modder/creator to prove you are innocent.
you will never get it changed to what you want bro.

**Comment by bluemods** [comment]
You can check everything here and let me know what you think:

https://github.com/bluemods/Bluecord
https://github.com/bluemods/BluecordPatcher

I tried my best to be respectful, the source code was put up in part to refute all claims of Bluecord being malicious, and I stand by my software 100%, and always will. The project was made with the sole purpose of providing users with a client with more features and giving people something more to enjoy. Anyone can doctor screenshots, fabricate things, etc., meanwhile my repos prove I've done nothing wrong.

I wish you the best of luck in your projects.

**Pull request closed without merging**
