### PR TITLE
Add Rikka

### PR DESCRIPTION
**Pull request by frolleks**
Continuation of #5

### CODE REVIEW

**Comment by sehnryr** [comment]
@frolleks Thanks for the PR, but it seems like the repo is still private. We cannot add a private client unless there is a way to get it elsewhere, like on a discord server. We'll add it when it is public.

**Comment by lexyclear** [comment]
nopery

**Comment by frolleks** [comment]
i'll tell you when its public

**Comment by frolleks** [comment]
I'm closing this PR, Git being goofy.

**Pull request closed without merging**
