### PR TITLE
Add `Rikka`

### PR DESCRIPTION
**Pull request by Frolleks**
While yes, the repository is currently private, but it will be public soon when the creator decides to.

### CODE REVIEW

**Review by lexyclear — APPROVED** [review]

**Comment by Frolleks** [comment]
deleted the branch due to unsolvable conflicts
i cant get access to my pc rn so i cant fix them

**Comment by lexyclear** [comment]
YO @frolleks is rikka going to go public anytime soon??

**Comment by frolleks** [comment]
> YO @frolleks is rikka going to go public anytime soon??

the development of this client mod slowed down, but i will ask the creator of it
when he responds i will tell you

**Comment by frolleks** [comment]
@lexyclear i got an update from him and he says that the settings page is barely even done

**Comment by frolleks** [comment]
@lexyclear update (again), he said hes gonna release it with the settings menu barely done

**Pull request closed without merging**
